apiVersion: v2
name: serviceexample
description: .NET Web API with MongoDB, Redis and NATS
type: application
version: 0.2.0
appVersion: "1.0.0"
annotations:
  artifacthub.io/license: MIT
  artifacthub.io/maintainers: |
    - name: Bluerate90
      email: your@email.com
